=== anyframejava/anyframe-ide/ide/plugins/org.anyframe.ide.common/xsds/anyframe-query-mapping-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.anyframejava.org/schema/query/mapping"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.anyframejava.org/schema/query/mapping">
		
	<!-- Top-level <queryservice> tag -->
	<xsd:element name="queryservice">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="table-mapping" minOccurs="0" maxOccurs="1"/>	
				<xsd:element ref="queries" minOccurs="0" maxOccurs="1"/>					
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!-- <table-mapping> tag -->
	<xsd:element name="table-mapping">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="table"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!-- <table> tag -->
	<xsd:element name="table">
		<xsd:annotation>
			<xsd:documentation>
			Define mapping information between table and class
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="field-mapping" minOccurs="1" maxOccurs="unbounded"/>
				<xsd:element ref="primary-key" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="class" type="xsd:string" use="required"/>						
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="field-mapping">
		<xsd:annotation>
			<xsd:documentation>
			Define table column and the attribute of mapping class
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dbms-column"/>
				<xsd:element ref="class-attribute"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="dbms-column">	
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="1" maxOccurs="1"/>
		</xsd:complexType>
	</xsd:element>	
		
	<xsd:element name="class-attribute">	
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="1" maxOccurs="1"/>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="primary-key">
		<xsd:annotation>
			<xsd:documentation>
			Define primary key of table
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dbms-column" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	
	
	<!-- <queries> tag -->
	<xsd:element name="queries">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="query"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
		
	<!-- <query> tag -->
	<xsd:element name="query">
		<xsd:annotation>
			<xsd:documentation>
			Define SQL statement to execute and class to save query execution result
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:group ref="queryElements"/>
			<xsd:attributeGroup ref="queryAttributes"/>		
		</xsd:complexType>
	</xsd:element>
	
	<xsd:attributeGroup name="queryAttributes">
		<xsd:attribute name="id" type="xsd:ID">
			<xsd:annotation>
				<xsd:documentation>
				Identifier to identify the relevant SQL statement.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="isDynamic" type="xsd:boolean" default="true">
			<xsd:annotation>
				<xsd:documentation>
				Identifies whether dynamic query or not.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="mappingStyle" default="camel">
			<xsd:annotation>
				<xsd:documentation>
				When mapping search result, 
				defines to which type the research column name should be modified.
				
				There are 4 styles:
				1. "camel"
				Change camel cased name to the search column name 
				2. "lower"
				Change lower cased name to the search column name 
				3. "upper"
				Change upper cased name to the search column name 
				4. "none"
				Apply what DBMS returned to the search column name
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="camel"/>
					<xsd:enumeration value="lower"/>
					<xsd:enumeration value="upper"/>
					<xsd:enumeration value="none"/>
				</xsd:restriction>
			</xsd:simpleType>			
		</xsd:attribute>
		<xsd:attribute name="maxFetchSize" type="xsd:int" use="optional">
			<xsd:annotation>
				<xsd:documentation>
				Controls maximum fetch-size of search result.
				Note: If the size of search result is over defined maxFetchSize, Exception occurred. 
				</xsd:documentation>
			</xsd:annotation>		
		</xsd:attribute>			
	</xsd:attributeGroup>
	
	<xsd:group name="queryElements">
		<xsd:sequence>
			<xsd:element ref="statement"/>
			<xsd:element ref="lobStatement" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="result" minOccurs="0" maxOccurs="1"/>								
		</xsd:sequence>
	</xsd:group>
	
	<xsd:element name="statement">
		<xsd:annotation>
			<xsd:documentation>
			Define SQL statement to execute.
			</xsd:documentation>
		</xsd:annotation>	
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="1" maxOccurs="1"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="lobStatement">
		<xsd:annotation>
			<xsd:documentation>
			To handle LOB data in Oracle 8i, in case of SQL statement to INSERT new LOB data,
			lobStatement tag must be additionally defined unlike general SQL statement definition.
			</xsd:documentation>			
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="statement"/>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>						
			</xsd:sequence>			
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="param">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
			Query service compiles the SQL statement and and saves it in PreparedStatement.
			Therefore, to execute setXXX in PreparedStatement for setting input value,
			define SQL type of the input parameter as the value of param tag attribute
			referring to the JDBC types defined in java.sql.Types.
			param tag is added according to input parameter number and order.
			To get parameter data, data type must be defined as the following.
	
			<Java Type>  				<DBMS Type>
			String 					:  	CHAR
			String					: 	VARCHAR
			String					: 	LONGVARCHAR
			java.math.BigDecimal	: 	NUMERIC
			java.math.BigDecimal	: 	DECIMAL
			boolean					: 	BIT
			byte					: 	TINYINT
			short					: 	SMALLINT
			int						:	INTEGER
			long					: 	BIGINT
			float					: 	REAL
			double					: 	FLOAT
			double					: 	DOUBLE
			byte[]					:	BINARY
			byte[]					:	VARBINARY
			byte[]					:	LONGVARBINARY
			java.sql.Date			:	DATE
			java.sql.Time			:	TIME
			java.sql.Timestamp		:	TIMESTAMP		
			]]></xsd:documentation>	
		</xsd:annotation>	
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="optional"/>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="binding" use="optional">
				<xsd:simpleType>
					<xsd:restriction base="xsd:NMTOKEN">
						<xsd:enumeration value="IN"/>
						<xsd:enumeration value="OUT"/>
						<xsd:enumeration value="INOUT"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="result">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
			Can be used when the query is SELECT statement and defines mapping class name for query execution result.
			If <result> is not defined, column and column value for the execution result of each row is put to Map as key 
			and value, and maps of each row will be returned as return value contained in list.						
			Note that key saved in Map is different according to the value of mappingStyle.
			For example, if value of mappingStyle is 'camel' and search column name is USER_NAME,
			key of map is userName.					
			]]></xsd:documentation>	
		</xsd:annotation>	
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="result-mapping" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>			
			<xsd:attribute name="length" type="xsd:int" use="optional"/>
			<xsd:attribute name="class" type="xsd:string" use="optional"/>	
			<xsd:attribute name="mapper" type="xsd:string" use="optional"/>		
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="result-mapping">
		<xsd:annotation>
			<xsd:documentation>
			Can be used when query is SELECT statement.
			Only when class to save query execution result and mapping table are not defined
			or when attribute name of class for result and mappingStyle-applied column name are not consistent,
			attribute name of the class mapping onto the column is defined.			
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="column" type="xsd:string" use="required" />
			<xsd:attribute name="attribute" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== anyframejava/anyframe-ide/plugin/optional/springrest/samples/anyframe-sample-springrest/src/main/resources/sql/query/mapping-query-movie.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryservice xmlns="http://www.anyframejava.org/schema/query/mapping" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.anyframejava.org/schema/query/mapping http://www.anyframejava.org/schema/query/mapping/anyframe-query-mapping-1.0.xsd ">
	<queries>
		<query id="createMovie">
			<statement>
				INSERT INTO MOVIE (movie_id, title, director, genre_id, actors, runtime, release_date, ticket_price, now_playing, poster_file)
				VALUES (:vo.movieId, :vo.title, :vo.director, :vo.genre.genreId, :vo.actors, :vo.runtime, :vo.releaseDate, :vo.ticketPrice, :vo.nowPlaying, :vo.posterFile)
			</statement>
		</query>

		<query id="updateMovie">
			<statement>
				UPDATE MOVIE 
				SET title = :vo.title,
				    director = :vo.director,
				    genre_id = :vo.genre.genreId,
				    actors = :vo.actors, 
				    runtime = :vo.runtime,
				    release_date = :vo.releaseDate,
				    ticket_price = :vo.ticketPrice,
				    now_playing = :vo.nowPlaying
				WHERE movie_id = :vo.movieId
			</statement>
		</query>

		<query id="removeMovie">
			<statement>
				DELETE FROM MOVIE 
				WHERE movie_id = :vo.movieId
			</statement>
		</query>

		<query id="findMovieByPk">
			<statement>
				SELECT movie_id, title, director, genre_id, actors, runtime, release_date, ticket_price, now_playing, poster_file
				FROM MOVIE
				WHERE movie_id = :vo.movieId
			</statement>
			<result class="org.anyframe.springrest.example.query.domain.Movie">
				<result-mapping column="{genre_id}" attribute="{genre.genreId}" />
			</result>
		</query>
		
		<query id="findMovieList">
			<statement>
				<!--query-findMovieList-START-->
				SELECT movie.movie_id, movie.title, movie.director, genre.name, movie.actors, movie.release_date, movie.now_playing, movie.poster_file, movie.ticket_price
				FROM MOVIE movie, GENRE genre
				WHERE movie.genre_id = genre.genre_id 
				AND title like '%' || :vo.title || '%'
				AND movie.now_playing = :vo.nowPlaying
				<!--query-findMovieList-END-->
			</statement>
			<result class="org.anyframe.springrest.example.query.domain.Movie">
				<result-mapping column="{name}" attribute="{genre.name}" />
			</result>
		</query>		
	</queries>
</queryservice>

=== anyframejava/anyframe-ide/plugin/optional/np-query/projects/anyframe-np-query-pi/src/main/webapp/WEB-INF/classes/sql/np-query/mapping-np-query-community.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryservice xmlns="http://www.anyframejava.org/schema/query/mapping" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.anyframejava.org/schema/query/mapping http://www.anyframejava.org/schema/query/mapping/anyframe-query-mapping-1.0.xsd ">

	<queries>
		<query id="findXPCommunityList" mappingStyle="upper">
			<statement>
			<!--np-query-findXPCommunityList-START-->
			SELECT
			COMMUNITY_ID, COMMUNITY_NAME, COMMUNITY_DESC, CATEGORY_ID, REG_ID, REG_DATE
			FROM XP_COMMUNITY
			<!--Velocity-Support-findXPCommunityList-START-->
			#if ($SEARCH_CONDITION.length() &gt; 0 &amp;&amp; "0" == $SEARCH_CONDITION)
				WHERE COMMUNITY_NAME like '%' || :SEARCH_KEYWORD || '%'
			#elseif ($SEARCH_CONDITION.length() &gt; 0 &amp;&amp; "1" == $SEARCH_CONDITION)
			    WHERE COMMUNITY_DESC like '%' || :SEARCH_KEYWORD || '%'
			#end
			<!--Velocity-Support-findXPCommunityList-END-->
			ORDER BY REG_DATE DESC		

		<!--np-query-findXPCommunityList-END-->
			</statement>
		</query>
		<query id="findXPCommunityListForTree" isDynamic="true" mappingStyle="upper">
			<statement>
			<!--np-query-findXPCommunityListForTree-START-->
			SELECT * FROM (
				SELECT	CATE.CATEGORY_ID, CATE.CATEGORY_NAME TEXT_NAME, CATE.CATEGORY_NAME, CATE.CATEGORY_DESC, CATE.REG_DATE CATE_REGDATE,
				'' COMMUNITY_ID, '' COMMUNITY_NAME,	'' COMMUNITY_DESC,	'' REG_ID, sysdate REG_DATE, 0 DEPTH
				FROM	XP_CATEGORY CATE

				UNION

				SELECT	COMM.CATEGORY_ID, COMM.COMMUNITY_NAME TEXT_NAME,'' CATEGORY_NAME, '' CATEGORY_DESC, sysdate REGDATE,
				COMM.COMMUNITY_ID,	COMM.COMMUNITY_NAME, COMM.COMMUNITY_DESC, COMM.REG_ID, COMM.REG_DATE, 1 DEPTH
				FROM XP_COMMUNITY COMM
				)
			ORDER BY CATEGORY_ID, DEPTH		

			<!--np-query-findXPCommunityListForTree-END-->
			</statement>
		</query>
		<query id="findXPCommunityListByCategory" mappingStyle="upper">
			<statement>
				SELECT
				COMMUNITY_ID, COMMUNITY_NAME, COMMUNITY_DESC, CATEGORY_ID, REG_ID, REG_DATE, '' UPDATE_YN
				FROM XP_COMMUNITY
				WHERE CATEGORY_ID = :CATEGORY_ID
				ORDER BY REG_DATE DESC
			</statement>
		</query>
		<query id="findXPCommunityListBySearchCondition" mappingStyle="upper">
			<statement>
			<!--np-query-findXPCommunityListBySearchCondition-START-->
			SELECT
			COMMUNITY_ID, COMMUNITY_NAME, COMMUNITY_DESC, CATEGORY_ID, REG_ID, REG_DATE
			FROM XP_COMMUNITY
			WHERE CATEGORY_ID = :CATEGORY_ID
			<!--Velocity-Support-findXPCommunityListBySearchCondition-START-->
			#if ($SEARCH_CONDITION.length() &gt; 0 &amp;&amp; "0" == $SEARCH_CONDITION)
				AND COMMUNITY_NAME like '%' || :SEARCH_KEYWORD || '%'
			#else
			    AND COMMUNITY_DESC like '%' || :SEARCH_KEYWORD || '%'
			#end
			<!--Velocity-Support-findXPCommunityListBySearchCondition-END-->
			ORDER BY REG_DATE DESC		

			<!--np-query-findXPCommunityListBySearchCondition-END-->
			</statement>
		</query>
		<query id="createXPCommunity" isDynamic="true" mappingStyle="upper">
			<statement>
			<!--np-query-createXPCommunity-START-->
			INSERT INTO XP_COMMUNITY
			(COMMUNITY_ID, COMMUNITY_NAME, COMMUNITY_DESC, REG_ID, REG_DATE, CATEGORY_ID)
			VALUES ('COMMUNITY-'|| NEXT VALUE FOR XP_COMMUNITY_ID_SEQ, :COMMUNITY_NAME, :COMMUNITY_DESC, :REG_ID, sysdate, :CATEGORY_ID)		

			<!--np-query-createXPCommunity-END-->
			</statement>
		</query>
		<query id="updateXPCommunity" isDynamic="true" mappingStyle="upper">
			<statement>
				UPDATE XP_COMMUNITY
				SET
				COMMUNITY_NAME = :COMMUNITY_NAME, COMMUNITY_DESC = :COMMUNITY_DESC, CATEGORY_ID =  :CATEGORY_ID, REG_ID = :REG_ID
				WHERE COMMUNITY_ID = :COMMUNITY_ID
			</statement>
		</query>
		<query id="removeXPCommunity" isDynamic="true" mappingStyle="upper">
			<statement>
				DELETE FROM XP_COMMUNITY
				WHERE COMMUNITY_ID = :COMMUNITY_ID
			</statement>
		</query>
	</queries>
</queryservice>

=== anyframejava/anyframe-ide/plugin/optional/xp-query/projects/anyframe-xp-query-pi/src/main/resources/sql/xp-query/mapping-xp-query-schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryservice xmlns="http://www.anyframejava.org/schema/query/mapping" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.anyframejava.org/schema/query/mapping http://www.anyframejava.org/schema/query/mapping/anyframe-query-mapping-1.0.xsd ">

	<queries>
		<query id="findXPScheduleList" isDynamic="true" mappingStyle="upper">
			<statement>
			<!--xp-query-findXPScheduleList-START-->
				SELECT SCHD_ID, USER_ID, SCHD_TITLE, SCHD_CONTENTS, SCHD_STARTDATE, SCHD_ENDDATE, SCHD_PLACE
				FROM XP_SCHD
				<!--Velocity-Support-findXPScheduleList-START-->
				#if ($SEARCH_CONDITION.length() &gt; 0 &amp;&amp; "0" == $SEARCH_CONDITION)
					WHERE SCHD_TITLE like '%' || :SEARCH_KEYWORD || '%'
				#end
				<!--Velocity-Support-findXPScheduleList-END-->
			<!--xp-query-findXPScheduleList-END-->
			</statement>
		</query>
		<query id="createXPSchedule" isDynamic="true" mappingStyle="upper">
			<statement>
			<!--xp-query-createXPSchedule-START-->
				INSERT INTO XP_SCHD
				(SCHD_ID, USER_ID, SCHD_TITLE, SCHD_CONTENTS, SCHD_STARTDATE, SCHD_ENDDATE, SCHD_PLACE)
				VALUES('SCHD-'|| NEXT VALUE FOR XP_SCHD_ID_SEQ, :USER_ID, :SCHD_TITLE, :SCHD_CONTENTS, :SCHD_STARTDATE, :SCHD_ENDDATE, :SCHD_PLACE)
			<!--xp-query-createXPSchedule-END-->
			</statement>
		</query>
		<query id="updateXPSchedule" isDynamic="true" mappingStyle="upper">
			<statement>
				UPDATE XP_SCHD
				SET
				SCHD_TITLE =:SCHD_TITLE, SCHD_CONTENTS =:SCHD_CONTENTS
				       , SCHD_STARTDATE =:SCHD_STARTDATE, SCHD_ENDDATE =:SCHD_ENDDATE, SCHD_PLACE =:SCHD_PLACE
				WHERE SCHD_ID=:SCHD_ID
			</statement>
		</query>
		<query id="removeXPSchedule" isDynamic="true" mappingStyle="upper">
			<statement>
				DELETE FROM XP_SCHD
				WHERE SCHD_ID=:SCHD_ID
			</statement>
		</query>
	</queries>
</queryservice>

=== anyframejava/anyframe-ide/plugin/optional/query/projects/anyframe-query/src/test/resources/mappings/testcase-queries-resultsetmapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryservice xmlns="http://www.anyframejava.org/schema/query/mapping" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.anyframejava.org/schema/query/mapping http://www.anyframejava.org/schema/query/mapping/anyframe-query-mapping-1.0.xsd ">

  	<queries>  		
  		<query id="findCustomerWithResultSetMapper" isDynamic="false">
  			<statement>select NAME, ADDRESS from TB_CUSTOMER where SSNO like ?</statement>
  			<param type="VARCHAR"/>
  			<result mapper="org.anyframe.query.mapper.CustomerMapper"/>
  		</query>  		
  		
  		<query id="findCustomerWithResultSetMapperAndLength" isDynamic="false">
  			<statement>select NAME, ADDRESS from TB_CUSTOMER where SSNO like ?</statement>
  			<param type="VARCHAR"/>
  			<result length="2" mapper="org.anyframe.query.mapper.CustomerMapper"/>
  		</query>   
  		
  		<query id="findCategoryListGeneral" isDynamic="false">
  			<statement>select * from TB_CATEGORY</statement>
  			<result class="org.anyframe.query.vo.CategoryVO"/>	  		
  		</query>  
  		
  		<query id="findCategoryListResultMapper" isDynamic="false">
  			<statement>select * from TB_CATEGORY</statement>
  			<result mapper="org.anyframe.query.mapper.CategoryMapper"/>	  		
  		</query>  
  		
  		<query id="findCategoryListHashMap" isDynamic="false">
  			<statement>select * from TB_CATEGORY</statement>		
  		</query>   		  		 				  							 			  						 				  			
    </queries>
    
</queryservice>

=== anyframejava/anyframe-ide/plugin/optional/simpleweb-jquery/projects/anyframe-simpleweb-jquery-pi/src/main/resources/sql/query/mapping-simpleweb-jquery-genre.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryservice xmlns="http://www.anyframejava.org/schema/query/mapping" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.anyframejava.org/schema/query/mapping http://www.anyframejava.org/schema/query/mapping/anyframe-query-mapping-1.0.xsd ">

	<queries>
		
		<query id="findJqueryGenreByPk">
			<statement>
				SELECT genre_id, name
				FROM JQUERY_GENRE
				WHERE genre_id = :vo.genreId
			</statement>
			<result class="org.anyframe.plugin.simpleweb.jquery.domain.Genre"/>
		</query>
		
		<query id="findDropDownJqueryGenreList" isDynamic="false">
			<statement>
				SELECT genre_id, name
				FROM JQUERY_GENRE
				ORDER BY name
			</statement>
			<result class="org.anyframe.plugin.simpleweb.jquery.domain.Genre" />
		</query>
		
		<query id="findGenreName">
			<statement>
			    <!--simpleweb-jquery-findGenreName-START-->
				SELECT name
				FROM JQUERY_GENRE
				WHERE name like :prefix || '%'
				<!--simpleweb-jquery-findGenreName-END-->
			</statement>
			<param type="VARCHAR" name="prefix"/>
		</query>
				
		<query id="findJqueryGenreList" isDynamic="true">
			<statement>
			    <!--simpleweb-jquery-findJqueryGenreList-START-->
				SELECT DISTINCT genre.genre_id, genre.name, CASE WHEN  movie.movie_id is not null THEN 'closed' ELSE movie.movie_id END state
				FROM JQUERY_GENRE genre
				LEFT JOIN JQUERY_MOVIE movie
				ON	genre.genre_id = movie.genre_id
				WHERE name like :vo.searchKeyword || '%'
				ORDER BY name
				<!--simpleweb-jquery-findJqueryGenreList-END-->
			</statement>
			<result class="org.anyframe.plugin.simpleweb.jquery.domain.Genre" />
		</query>
		
		<query id="findGenreListForTree" isDynamic="true">
			<statement>
			    <!--simpleweb-jquery-findGenreListForTree-START-->
				SELECT genre.genre_id, genre.name, CASE WHEN  movie.movie_id is not null THEN 'closed' ELSE movie.movie_id END state
				FROM JQUERY_GENRE genre
				LEFT JOIN JQUERY_MOVIE movie
				ON	genre.genre_id = movie.genre_id
				WHERE name like :vo.searchKeyword || '%'
				ORDER BY name
				<!--simpleweb-jquery-findGenreListForTree-END-->
			</statement>
			<result class="org.anyframe.plugin.simpleweb.jquery.domain.Genre" />
		</query>
		
	</queries>
</queryservice>

=== anyframejava/anyframe-ide/plugin/optional/jquery/projects/anyframe-jquery-pi/src/main/resources/sql/query/mapping-jquery-community.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryservice xmlns="http://www.anyframejava.org/schema/query/mapping" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.anyframejava.org/schema/query/mapping http://www.anyframejava.org/schema/query/mapping/anyframe-query-mapping-1.0.xsd ">

	<queries>
		<query id="updateJqueryCommunity">
			<statement>
				UPDATE JQUERY_COMMUNITY
				SET COMMUNITY_NAME = :vo.communityName,
					COMMUNITY_DESC = :vo.communityDesc
				WHERE COMMUNITY_ID = :vo.communityId
			</statement>
		</query>
		<query id="findJqueryCommunityList" isDynamic="true">
			<statement>
			<![CDATA[
				SELECT 
					community.COMMUNITY_ID, community.COMMUNITY_NAME, community.COMMUNITY_DESC, community.CATEGORY_ID, community.REG_ID, community.REG_DATE
				FROM JQUERY_COMMUNITY community
			]]>
			</statement>
			<result class="org.anyframe.plugin.jquery.communityfinder.domain.Community"/>
		</query>
		<query id="findJqueryCommunityByPk">
			<statement>
				SELECT 
					community.COMMUNITY_ID, community.COMMUNITY_NAME, community.COMMUNITY_DESC, community.CATEGORY_ID, community.REG_ID, community.REG_DATE
				FROM JQUERY_COMMUNITY community
				WHERE COMMUNITY_ID = :vo.communityId
			</statement>
			<result class="org.anyframe.plugin.jquery.communityfinder.domain.Community"/>
		</query>
        <query id="findDropDownJqueryCommunityNameList" isDynamic="true">
            <statement>
                SELECT
                COMMUNITY_ID, COMMUNITY_NAME
                FROM JQUERY_COMMUNITY
                ORDER BY COMMUNITY_NAME
            </statement>
            <result class="org.anyframe.plugin.jquery.communityfinder.domain.Community"/>
        </query>
	</queries>
</queryservice>

=== anyframejava/anyframe-ide/plugin/optional/mip-query/projects/anyframe-mip-query-pi/src/main/resources/sql/mip-query/mapping-mip-query-community.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryservice xmlns="http://www.anyframejava.org/schema/query/mapping" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.anyframejava.org/schema/query/mapping http://www.anyframejava.org/schema/query/mapping/anyframe-query-mapping-1.0.xsd ">

	<queries>
		<query id="findCommunityList" mappingStyle="upper">
			<statement>
			<!--mip-query-findCommunityList-START-->
				SELECT
				COMMUNITY_ID, COMMUNITY_NAME, COMMUNITY_DESC, CATEGORY_ID, REG_ID, REG_DATE
				FROM MIP_COMMUNITY
				<!--Velocity-Support-findCommunityList-START-->
				#if ($SEARCH_CONDITION.length() &gt; 0 &amp;&amp; "0" == $SEARCH_CONDITION)
					WHERE COMMUNITY_NAME like '%' || :SEARCH_KEYWORD || '%'
				#elseif ($SEARCH_CONDITION.length() &gt; 0 &amp;&amp; "1" == $SEARCH_CONDITION)
				    WHERE COMMUNITY_DESC like '%' || :SEARCH_KEYWORD || '%'
				#end
				<!--Velocity-Support-findCommunityList-END-->
				ORDER BY REG_DATE DESC
			<!--mip-query-findCommunityList-END-->
			</statement>
		</query>
		<query id="findCommunityListForTree" isDynamic="true" mappingStyle="upper">
			<statement>
			<!--mip-query-findCommunityListForTree-START-->
				SELECT * FROM (
					SELECT	CATE.CATEGORY_ID, CATE.CATEGORY_NAME TEXT_NAME, CATE.CATEGORY_NAME, CATE.CATEGORY_DESC, CATE.REG_DATE CATE_REGDATE,
					'' COMMUNITY_ID, '' COMMUNITY_NAME,	'' COMMUNITY_DESC,	'' REG_ID, sysdate REG_DATE, 0 DEPTH
					FROM	MIP_CATEGORY CATE

					UNION

					SELECT	COMM.CATEGORY_ID, COMM.COMMUNITY_NAME TEXT_NAME,'' CATEGORY_NAME, '' CATEGORY_DESC, sysdate REGDATE,
					COMM.COMMUNITY_ID,	COMM.COMMUNITY_NAME, COMM.COMMUNITY_DESC, COMM.REG_ID, COMM.REG_DATE, 1 DEPTH
					FROM MIP_COMMUNITY COMM
					)
					ORDER BY CATEGORY_ID, DEPTH
			<!--mip-query-findCommunityListForTree-END-->
			</statement>
		</query>
		<query id="findCommunityListByCategory" mappingStyle="upper">
			<statement>
				SELECT
				COMMUNITY_ID, COMMUNITY_NAME, COMMUNITY_DESC, CATEGORY_ID, REG_ID, REG_DATE, '' UPDATE_YN
				FROM MIP_COMMUNITY
				WHERE CATEGORY_ID = :CATEGORY_ID
				ORDER BY REG_DATE DESC
			</statement>
		</query>
		<query id="findCommunityListBySearchCondition" mappingStyle="upper">
			<statement>
			<!--mip-query-findCommunityListBySearchCondition-START-->
				SELECT
				COMMUNITY_ID, COMMUNITY_NAME, COMMUNITY_DESC, CATEGORY_ID, REG_ID, REG_DATE
				FROM MIP_COMMUNITY
				WHERE CATEGORY_ID = :CATEGORY_ID
				<!--Velocity-Support-findCommunityListBySearchCondition-START-->
				#if ($SEARCH_CONDITION.length() &gt; 0 &amp;&amp; "0" == $SEARCH_CONDITION)
					AND COMMUNITY_NAME like '%' || :SEARCH_KEYWORD || '%'
				#else
				    AND COMMUNITY_DESC like '%' || :SEARCH_KEYWORD || '%'
				#end
				<!--Velocity-Support-findCommunityListBySearchCondition-END-->
				ORDER BY REG_DATE DESC
			<!--mip-query-findCommunityListBySearchCondition-END-->
			</statement>
		</query>
		<query id="createCommunity" isDynamic="true" mappingStyle="upper">
			<statement>
			<!--mip-query-createCommunity-START-->
				INSERT INTO MIP_COMMUNITY
				(COMMUNITY_ID, COMMUNITY_NAME, COMMUNITY_DESC, REG_ID, REG_DATE, CATEGORY_ID)
				VALUES ('COMMUNITY-'|| NEXT VALUE FOR COMMUNITY_ID_SEQ, :COMMUNITY_NAME, :COMMUNITY_DESC, :REG_ID, sysdate, :CATEGORY_ID)
			<!--mip-query-createCommunity-END-->
			</statement>
		</query>
		<query id="updateCommunity" isDynamic="true" mappingStyle="upper">
			<statement>
				UPDATE MIP_COMMUNITY
				SET
				COMMUNITY_NAME = :COMMUNITY_NAME, COMMUNITY_DESC = :COMMUNITY_DESC, CATEGORY_ID =  :CATEGORY_ID, REG_ID = :REG_ID
				WHERE COMMUNITY_ID = :COMMUNITY_ID
			</statement>
		</query>
		<query id="removeCommunity" isDynamic="true" mappingStyle="upper">
			<statement>
				DELETE FROM MIP_COMMUNITY
				WHERE COMMUNITY_ID = :COMMUNITY_ID
			</statement>
		</query>
	</queries>
</queryservice>
